### ISSUE TITLE
Test failure in testthat/test-display.R

### ISSUE THREAD

**Issue by bruc** [Nowosad/rcartocolor#3]
I'm trying to run the tests that come with rcartocolor and when running "R CMD check" on this package, I get the following error:
```
Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(rcartocolor)
  > 
  > test_check("rcartocolor")
  ── 1. Failure: palette display (@test-display.R#4)  ────────────────────────────
  `display_carto_all(n = NULL)` produced warnings.
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 27 SKIPPED: 4 FAILED: 1
  1. Failure: palette display (@test-display.R#4) 
  
  Error: testthat unit tests failed
  Execution halted
* DONE
Status: 1 ERROR, 1 NOTE
```
The code line in question is 
```
expect_silent(display_carto_all(n = NULL))
```

So, I tried running this directly in R-3.5.2, and here's what I get:
```
> library(rcartocolor)
> display_carto_all(n = NULL)
Warning message:
Detecting old grouped_df format, replacing `vars` attribute by `groups` 
> 
```
I don't know R well enough to understand this message, but it looks like R has changed to cause the display_carto_all function to generate warnings now.

Can this problem be fixed and a new versions of rcartocolor be uploaded to CRAN?

**Comment by Nowosad** [comment]
Hi @bruc , thanks for opening the issue.
What's the version you're using? I think I've solved this problem a few days ago - https://github.com/Nowosad/rcartocolor/commit/3163946af881b48f095d8b6f92c55d641770f469.

Can you try the version 1.0.0 and let me know if it works properly?

**Comment by bruc** [comment]
Thanks for replying. I was running 0.0.22 which had the failure. I just installed 1.0.0 from CRAN and it passed the R CMD check test. Thanks!!

You can close this issue.

**Comment by Nowosad** [comment]
Great.
