### ISSUE TITLE
Option for choosing colorblind-friendly palettes?

### ISSUE THREAD

**Issue by tungttnguyen** [Nowosad/rcartocolor#5]
Hello,

This is a great package with some beautiful color palettes. I'm wondering if it's possible to add a `colorblindFriendly` option to help users pick colorblind friendly palettes? 

Thanks!

``` r
library(RColorBrewer)

RColorBrewer::display.brewer.all(colorblindFriendly = TRUE)
```

![](https://i.imgur.com/NV7Ni8Y.png)

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by Nowosad** [comment]
Thanks for the idea! I will try to work on it (however, I am unsure when yet).

**Comment by Nowosad** [comment]
Hi @tungmilan ,

I've added an option `colorblind_friendly` to the `display_carto_all()` function. Right not it is just on github, so you need to install it with:

```
remotes::install_github("Nowosad/rcartocolor")
```
And next:

``` r
library(rcartocolor)
display_carto_all(colorblind_friendly = TRUE)
```

![](https://i.imgur.com/avzBEhS.png)

<sup>Created on 2019-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

You can also find out why some of the packages are colorblind friendly and some are not at https://nowosad.github.io/colorblindcheck/articles/articles/check_rcartocolor.html.

Please, try this option and let me know if it works as expected.

**Comment by tungttnguyen** [comment]
@Nowosad Thank you very much! This is very useful! And the `colorblindcheck` package is a great addition as well. I'm gonna use it together with the [colorblindr](https://github.com/clauswilke/colorblindr) package in the future.

**Comment by Nowosad** [comment]
Great! Feel free to suggest any changes or improvements;)

**Comment by tungttnguyen** [comment]
Hi @Nowosad . Just a thought. Would it be better to replace the color maps used in the package examples (`Fall` & `Prism`) with colorblind-friendly ones?

**Comment by Nowosad** [comment]
Great idea @tungmilan - how about now - https://github.com/Nowosad/rcartocolor?

**Comment by tungttnguyen** [comment]
Looks good @Nowosad !
